changelog:
  exclude:
    authors:
      - pre-commit-ci
    labels:
      - no-changelog-entry-needed
      - skip-changelog

  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: New Features
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
