version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
