# Configuration items specific to the glue.core sub-package

__all__ = ['SUBSET_COLORS', 'DEFAULT_COLOR', 'DEFAULT_SUBSET_COLOR']

GREY = '#373737'
GRAY = GREY
BLUE = "#1F78B4"
GREEN = "#33A02C"
RED = "#E31A1C"
ORANGE = "#FF7F00"
PURPLE = "#6A3D9A"
YELLOW = "#FFFF99"
BROWN = "#8C510A"
PINK = "#FB9A99"
LIGHT_BLUE = "#A6CEE3"
LIGHT_GREEN = "#B2DF8A"
LIGHT_RED = "#FB9A99"
LIGHT_ORANGE = "#FDBF6F"
LIGHT_PURPLE = "#CAB2D6"

SUBSET_COLORS = [RED, GREEN, BLUE, BROWN, ORANGE, PURPLE, PINK]
DEFAULT_COLOR = GRAY
DEFAULT_SUBSET_COLOR = RED