# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scatterwidget.ui'
#
# Created: Wed Feb 29 17:18:25 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ScatterWidget(object):
    def setupUi(self, ScatterWidget):
        ScatterWidget.setObjectName(_fromUtf8("ScatterWidget"))
        ScatterWidget.resize(823, 752)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ScatterWidget)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(ScatterWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(7)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.mplWidget = MplWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplWidget.sizePolicy().hasHeightForWidth())
        self.mplWidget.setSizePolicy(sizePolicy)
        self.mplWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.mplWidget.setToolTip(_fromUtf8(""))
        self.mplWidget.setObjectName(_fromUtf8("mplWidget"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.axisLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.axisLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.axisLayout.setMargin(0)
        self.axisLayout.setObjectName(_fromUtf8("axisLayout"))
        self.xAxisLayout = QtGui.QHBoxLayout()
        self.xAxisLayout.setObjectName(_fromUtf8("xAxisLayout"))
        self.xlabel = QtGui.QLabel(self.layoutWidget)
        self.xlabel.setObjectName(_fromUtf8("xlabel"))
        self.xAxisLayout.addWidget(self.xlabel)
        self.xAxisComboBox = QtGui.QComboBox(self.layoutWidget)
        self.xAxisComboBox.setObjectName(_fromUtf8("xAxisComboBox"))
        self.xAxisLayout.addWidget(self.xAxisComboBox)
        self.xLogCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.xLogCheckBox.setObjectName(_fromUtf8("xLogCheckBox"))
        self.xAxisLayout.addWidget(self.xLogCheckBox)
        self.xFlipCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.xFlipCheckBox.setObjectName(_fromUtf8("xFlipCheckBox"))
        self.xAxisLayout.addWidget(self.xFlipCheckBox)
        self.axisLayout.addLayout(self.xAxisLayout)
        self.yAxisLayout = QtGui.QHBoxLayout()
        self.yAxisLayout.setObjectName(_fromUtf8("yAxisLayout"))
        self.ylabel = QtGui.QLabel(self.layoutWidget)
        self.ylabel.setObjectName(_fromUtf8("ylabel"))
        self.yAxisLayout.addWidget(self.ylabel)
        self.yAxisComboBox = QtGui.QComboBox(self.layoutWidget)
        self.yAxisComboBox.setObjectName(_fromUtf8("yAxisComboBox"))
        self.yAxisLayout.addWidget(self.yAxisComboBox)
        self.yLogCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.yLogCheckBox.setObjectName(_fromUtf8("yLogCheckBox"))
        self.yAxisLayout.addWidget(self.yLogCheckBox)
        self.yFlipCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.yFlipCheckBox.setObjectName(_fromUtf8("yFlipCheckBox"))
        self.yAxisLayout.addWidget(self.yFlipCheckBox)
        self.axisLayout.addLayout(self.yAxisLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.axisLayout.addItem(spacerItem)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layerTree = QtGui.QTreeWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.layerTree.sizePolicy().hasHeightForWidth())
        self.layerTree.setSizePolicy(sizePolicy)
        self.layerTree.setMinimumSize(QtCore.QSize(0, 0))
        self.layerTree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layerTree.setObjectName(_fromUtf8("layerTree"))
        self.verticalLayout.addWidget(self.layerTree)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.layerAddButton = QtGui.QPushButton(self.layoutWidget1)
        self.layerAddButton.setStatusTip(_fromUtf8(""))
        self.layerAddButton.setWhatsThis(_fromUtf8(""))
        self.layerAddButton.setObjectName(_fromUtf8("layerAddButton"))
        self.horizontalLayout.addWidget(self.layerAddButton)
        self.layerRemoveButton = QtGui.QPushButton(self.layoutWidget1)
        self.layerRemoveButton.setEnabled(False)
        self.layerRemoveButton.setObjectName(_fromUtf8("layerRemoveButton"))
        self.horizontalLayout.addWidget(self.layerRemoveButton)
        self.linkButton = QtGui.QPushButton(self.layoutWidget1)
        self.linkButton.setObjectName(_fromUtf8("linkButton"))
        self.horizontalLayout.addWidget(self.linkButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.splitter_2)

        self.retranslateUi(ScatterWidget)
        QtCore.QMetaObject.connectSlotsByName(ScatterWidget)
        ScatterWidget.setTabOrder(self.xAxisComboBox, self.xLogCheckBox)
        ScatterWidget.setTabOrder(self.xLogCheckBox, self.xFlipCheckBox)
        ScatterWidget.setTabOrder(self.xFlipCheckBox, self.yAxisComboBox)
        ScatterWidget.setTabOrder(self.yAxisComboBox, self.yLogCheckBox)
        ScatterWidget.setTabOrder(self.yLogCheckBox, self.yFlipCheckBox)

    def retranslateUi(self, ScatterWidget):
        ScatterWidget.setWindowTitle(QtGui.QApplication.translate("ScatterWidget", "Scatter Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.xlabel.setText(QtGui.QApplication.translate("ScatterWidget", "x axis", None, QtGui.QApplication.UnicodeUTF8))
        self.xAxisComboBox.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Set which attribute is plotted on the x axis", None, QtGui.QApplication.UnicodeUTF8))
        self.xLogCheckBox.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Toggle on/off log scaling on the x axis", None, QtGui.QApplication.UnicodeUTF8))
        self.xLogCheckBox.setText(QtGui.QApplication.translate("ScatterWidget", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.xFlipCheckBox.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Flip/unflip the order of the x axis", None, QtGui.QApplication.UnicodeUTF8))
        self.xFlipCheckBox.setText(QtGui.QApplication.translate("ScatterWidget", "flip", None, QtGui.QApplication.UnicodeUTF8))
        self.ylabel.setText(QtGui.QApplication.translate("ScatterWidget", "y axis", None, QtGui.QApplication.UnicodeUTF8))
        self.yAxisComboBox.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Set which attribute is plotted on the y axis", None, QtGui.QApplication.UnicodeUTF8))
        self.yLogCheckBox.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Toggle on/off log scaling on the y axis", None, QtGui.QApplication.UnicodeUTF8))
        self.yLogCheckBox.setText(QtGui.QApplication.translate("ScatterWidget", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.yFlipCheckBox.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Flip/unflip the order of the y axis", None, QtGui.QApplication.UnicodeUTF8))
        self.yFlipCheckBox.setText(QtGui.QApplication.translate("ScatterWidget", "flip", None, QtGui.QApplication.UnicodeUTF8))
        self.layerTree.headerItem().setText(0, QtGui.QApplication.translate("ScatterWidget", "Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.layerTree.headerItem().setText(1, QtGui.QApplication.translate("ScatterWidget", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.layerTree.headerItem().setText(2, QtGui.QApplication.translate("ScatterWidget", "Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.layerTree.headerItem().setText(3, QtGui.QApplication.translate("ScatterWidget", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.layerAddButton.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Add a new subset or data set", None, QtGui.QApplication.UnicodeUTF8))
        self.layerAddButton.setText(QtGui.QApplication.translate("ScatterWidget", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.layerRemoveButton.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Remove a subset or data set from all visualizations", None, QtGui.QApplication.UnicodeUTF8))
        self.layerRemoveButton.setText(QtGui.QApplication.translate("ScatterWidget", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.linkButton.setToolTip(QtGui.QApplication.translate("ScatterWidget", "Link subsets", None, QtGui.QApplication.UnicodeUTF8))
        self.linkButton.setText(QtGui.QApplication.translate("ScatterWidget", "Link", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
